### ISSUE TITLE
Spark generates very long module names causing compile errors on some systems

### ISSUE THREAD

**Issue by jimsynz** [ash-project/spark#103]
**Describe the bug**
Deeply nested DSLs create module names such as `Elixir.Wayfarer.Dsl.Wayfarer.Config.Wayfarer.Targets.Targets.Wayfarer.Targets.Targets.Http.Wayfarer.Targets.Targets.HealthChecks.HealthChecks` which will trigger `enametoolong` on some systems:

```
08:20:24.969 [error] Process #PID<0.153.0> raised an exception
** (File.Error) could not write to file "/home/james/Dev/harton.dev/james/wayfarer/_build/dev/lib/wayfarer/ebin/Elixir.Wayfarer.Dsl.Wayfarer.Config.Wayfarer.Targets.Targets.Wayfarer.Targets.Targets.Http.Wayfarer.Targets.Targets.HealthChecks.HealthChecks.beam": file name too long
    (elixir 1.17.1) lib/file.ex:1144: File.write!/3
    (elixir 1.17.1) lib/kernel/parallel_compiler.ex:334: anonymous fn/3 in Kernel.ParallelCompiler.write_module_binaries/3
    (elixir 1.17.1) lib/enum.ex:1268: anonymous fn/3 in Enum.flat_map/2
    (stdlib 6.0) maps.erl:860: :maps.fold_1/4
    (elixir 1.17.1) lib/enum.ex:2543: Enum.flat_map/2
    (elixir 1.17.1) lib/kernel/parallel_compiler.ex:261: Kernel.ParallelCompiler.spawn_workers/3
    (mix 1.17.1) lib/mix/compilers/elixir.ex:1018: anonymous fn/9 in Mix.Compilers.Elixir.compiler_loop/6
```

To be clear this an issue with BEAM and not Spark or Elixir and in response to [a similar bug report against Elixir](https://github.com/elixir-lang/elixir/issues/12552) José's response boils down to "just use shorter module names". I think he's right. There are a couple of strategies I can think of; 

1. Move generated modules out of the `Elixir.` namespace (I suggest `Spark.`).
2. Name modules by using a hash of their DSL path. I'd suggest `:erlang.phash2` since it should always be available. It doesn't really matter if the modules are "discoverable" as they're only ever imported by Spark anyway. We can always add a flag to disable this behaviour while debugging.

**To Reproduce**
I triggered it by using [eCryptfs](https://www.ecryptfs.org/) on a portable Linux device because the effective file length limit is ~140 bytes. It is possible to reproduce on Linux & macOS (255 byte limit) by creating a DSL with very long entity names.

**Expected behavior**
The DSL extension should cleanly compile.

**Runtime**
 - Elixir version `1.17.1`
 - Erlang version `27.0`
 - OS Linux 5.10.17-v8+ aarch64. Raspberry Pi OS based on Debian 11 (bullseye).
 - Spark version `2.2.4`
 - any related extension versions

**Additional context**

**Comment by zachdaniel** [comment]
Open to any of these. The generated modules are hidden and any public use of them is incorrect. So honestly I'm down for "anything that works" 😅

**Comment by zachdaniel** [comment]
@jimsynz if you've got some time to tackle this that would be great, got a lot on ye olde plate at the moment.

**Comment by jimsynz** [comment]
Yeah, I've added it to my list :)

**Comment by svallory** [comment]
Hey guys, I'm trying to write a DSL for the [RCS Standard](https://developers.google.com/business-communications/rcs-business-messaging/reference/rest/v1/phones.agentMessages#ContentInfo) and I just stumbled upon this.

What strikes me as odd though is the amount of repetition in the path. Is Spark automatically creating sections with the same name as the entities?

```
[error] [label: {:erl_prim_loader, :file_error}, report: ~c"File operation error: enametoolong. Target: /work/rcs/rcs-lang/_build/dev/lib/rcs_lang/ebin/Elixir.AgentMessage.Extension.AgentMessageRoot.AgentMessage.ContentMessage.ContentMessage.RichCard.RichCard.CarouselCard.CarouselCard.CardContent.CardContent.Suggestion.Suggestion.Action.Action.ViewLocationAction.ViewLocationAction.LatLong.LatLong.Options.beam. Function: read_file. Process: code_server."]
```

Here's my extension:

```elixir
defmodule AgentMessage.Extension do
  @moduledoc """
  A Spark.Dsl.Extension for defining AgentMessage DSLs.
  """

  # Schema definitions
  @postback_data_schema [
    type: :string,
    required: true,
    doc: "Arbitrary data that is passed to the agent when a user taps a suggestion. Maximum 2048 characters."
  ]

  # Basic Action Entities (no nesting)
  @dial_action %Spark.Dsl.Entity{
    name: :dialAction,
    target: AgentMessage.Structs.DialAction,
    describe: "Opens the user's default dialer app with the specified phone number.",
    schema: [ phoneNumber: [type: :string, required: true, doc: "The phone number to dial."] ]
  }

  @open_url_action %Spark.Dsl.Entity{
    name: :openUrlAction,
    target: AgentMessage.Structs.OpenUrlAction,
    describe: "Opens a URL in the default browser.",
    schema: [ url: [type: :string, required: true, doc: "The URL to open. Maximum 2048 characters. (Format: URI)"] ]
  }

  @share_location_action %Spark.Dsl.Entity{
    name: :shareLocationAction,
    target: AgentMessage.Structs.ShareLocationAction,
    describe: "Requests the user to share their location."
  }

  @create_calendar_event_action %Spark.Dsl.Entity{
    name: :createCalendarEventAction,
    target: AgentMessage.Structs.CreateCalendarEventAction,
    describe: "Opens the user's default calendar app to create an event.",
    schema: [
      startTime: [type: :string, required: true, doc: "Start time for the event (ISO 8601 format)."],
      endTime: [type: :string, required: true, doc: "End time for the event (ISO 8601 format)."],
      title: [type: :string, required: true, doc: "The title of the calendar event."],
      description: [type: :string, doc: "Optional. The description of the calendar event."]
    ]
  }

  # LatLong entity (minimal nesting)
  @lat_long %Spark.Dsl.Entity{
    name: :latLong,
    target: AgentMessage.Structs.ViewLocationAction.LatLong,
    describe: "The latitude and longitude of the location.",
    schema: [
      latitude: [type: :float, required: true, doc: "The latitude of the location."],
      longitude: [type: :float, required: true, doc: "The longitude of the location."]
    ]
  }

  @view_location_action %Spark.Dsl.Entity{
    name: :viewLocationAction,
    target: AgentMessage.Structs.ViewLocationAction,
    describe: "Opens the user's default map app with the specified location.",
    schema: [
      label: [type: :string, doc: "Optional. A label for the map marker."],
      query: [type: :string, doc: "A query to search for a location."]
    ],
    entities: [ latLong: [@lat_long] ]
  }

  # Compose action entities
  @compose_text_message %Spark.Dsl.Entity{
    name: :composeTextMessage,
    target: AgentMessage.Structs.ComposeAction.ComposeTextMessage,
    describe: "Details for composing a text message.",
    schema: [
      phoneNumber: [type: :string, required: true, doc: "Prefilled destination phone number."],
      text: [type: :string, required: true, doc: "Draft to go into the send message text field."]
    ]
  }

  @compose_recording_message %Spark.Dsl.Entity{
    name: :composeRecordingMessage,
    target: AgentMessage.Structs.ComposeAction.ComposeRecordingMessage,
    describe: "Details for composing a recording message (audio or video).",
    schema: [
      phoneNumber: [type: :string, required: true, doc: "Prefilled destination phone number."],
      type: [type: {:one_of, [:COMPOSE_RECORDING_ACTION_TYPE_UNSPECIFIED, :ACTION_TYPE_AUDIO, :ACTION_TYPE_VIDEO]}, required: true, doc: "The type of the recording action."]
    ]
  }

  @compose_action %Spark.Dsl.Entity{
    name: :composeAction,
    target: AgentMessage.Structs.ComposeAction,
    describe: "Opens a compose message interface.",
    entities: [
      composeTextMessage: [@compose_text_message],
      composeRecordingMessage: [@compose_recording_message]
    ]
  }

  # Content entities
  @content_info %Spark.Dsl.Entity{
    name: :contentInfo,
    target: AgentMessage.Structs.ContentInfo,
    describe: "Information about a file hosted at a public URL.",
    schema: [
      fileUrl: [type: :string, required: true, doc: "Publicly hosted URL of the file."],
      thumbnailUrl: [type: :string, doc: "Optional thumbnail URL."],
      forceRefresh: [type: :boolean, doc: "Force refresh of cached content."]
    ]
  }

  @media %Spark.Dsl.Entity{
    name: :media,
    target: AgentMessage.Structs.Media,
    describe: "Media to display in a rich card.",
    schema: [ height: [type: {:one_of, [:HEIGHT_UNSPECIFIED, :SHORT, :MEDIUM, :TALL]}, required: true, doc: "The height of the media."] ],
    entities: [ contentInfo: [@content_info] ]
  }

  # Suggestion entities
  @reply %Spark.Dsl.Entity{
    name: :reply,
    target: AgentMessage.Structs.SuggestedReply,
    args: [:text, :postbackData],
    describe: "A suggested reply that the user can tap to send.",
    schema: [
      text: [type: :string, required: true, doc: "The text of the suggested reply. Max 25 chars."],
      postbackData: @postback_data_schema
    ]
  }

  @action %Spark.Dsl.Entity{
    name: :action,
    target: AgentMessage.Structs.SuggestedAction,
    describe: "A suggested action that the user can tap.",
    schema: [
      text: [type: :string, required: true, doc: "The text of the suggested action. Max 25 chars."],
      postbackData: @postback_data_schema,
      fallbackUrl: [type: :string, doc: "Optional fallback URL. Max 2048 chars."]
    ],
    entities: [
      dialAction: [@dial_action],
      openUrlAction: [@open_url_action],
      shareLocationAction: [@share_location_action],
      viewLocationAction: [@view_location_action],
      createCalendarEventAction: [@create_calendar_event_action],
      composeAction: [@compose_action]
    ]
  }

  @suggestion %Spark.Dsl.Entity{
    name: :suggestion,
    target: AgentMessage.Structs.Suggestion,
    describe: "A suggestion that the user can tap.",
    entities: [
      reply: [@reply],
      action: [@action]
    ]
  }

  # Card entities
  @card_content %Spark.Dsl.Entity{
    name: :cardContent,
    target: AgentMessage.Structs.CardContent,
    describe: "The content of a rich card.",
    schema: [
      title: [type: :string, doc: "Optional. The title of the card. Maximum 200 characters."],
      description: [type: :string, doc: "Optional. The description of the card. Maximum 2000 characters."]
    ],
    entities: [
      media: [@media],
      suggestion: [@suggestion]
    ]
  }

  @carousel_card %Spark.Dsl.Entity{
    name: :carouselCard,
    target: AgentMessage.Structs.CarouselCard,
    describe: "A carousel of rich cards.",
    schema: [ cardWidth: [type: {:one_of, [:CARD_WIDTH_UNSPECIFIED, :SMALL, :MEDIUM]}, required: true, doc: "The width of the cards in the carousel."] ],
    entities: [ cardContent: [@card_content] ]
  }

  @standalone_card %Spark.Dsl.Entity{
    name: :standaloneCard,
    target: AgentMessage.Structs.StandaloneCard,
    describe: "A standalone rich card.",
    schema: [
      cardOrientation: [type: {:one_of, [:CARD_ORIENTATION_UNSPECIFIED, :HORIZONTAL, :VERTICAL]}, required: true, doc: "Orientation of the card."],
      thumbnailImageAlignment: [type: {:one_of, [:THUMBNAIL_IMAGE_ALIGNMENT_UNSPECIFIED, :LEFT, :RIGHT]}, doc: "Optional. Image preview alignment for standalone cards with horizontal layout."]
    ],
    entities: [ cardContent: [@card_content] ]
  }

  @rich_card %Spark.Dsl.Entity{
    name: :richCard,
    target: AgentMessage.Structs.RichCard,
    describe: "A rich card. Can be a standalone card or a carousel of cards.",
    entities: [
      carouselCard: [@carousel_card],
      standaloneCard: [@standalone_card]
    ]
  }

  # Main content message entity
  @content_message %Spark.Dsl.Entity{
    name: :contentMessage,
    target: AgentMessage.Structs.AgentContentMessage,
    describe: "The content of a message.",
    schema: [
      text: [type: :string, doc: "UTF-8 encoded text. Maximum 2048 characters."],
      fileName: [type: :string, doc: "The name of a file on the user's device."],
      uploadedRbmFile: [type: :struct, doc: "An RBM file previously uploaded by the agent."],
      richCard: [type: :struct, doc: "A rich card (standalone or carousel)."],
      contentInfo: [type: :struct, doc: "Information about a file hosted at a public URL."]
    ],
    entities: [
      richCard: [@rich_card],
      suggestion: [@suggestion]
    ]
  }

  # Root agent message entity
  @agent_message %Spark.Dsl.Entity{
    name: :agentMessage,
    target: AgentMessage.Structs.AgentMessage,
    describe: "Defines a complete AgentMessage.",
    schema: [
      messageTrafficType: [
        type: {:one_of, [
          :MESSAGE_TRAFFIC_TYPE_UNSPECIFIED,
          :AUTHENTICATION,
          :TRANSACTION,
          :PROMOTION,
          :SERVICEREQUEST,
          :ACKNOWLEDGEMENT
        ]},
        required: true,
        doc: "Supported message traffic types."
      ],
      expireTime: [type: :string, doc: "Optional. Timestamp in UTC of when this resource is considered expired."],
      ttl: [type: :string, doc: "Optional. How long the message will live before it is automatically revoked."]
    ],
    entities: [ contentMessage: [@content_message] ]
  }

  @agent_message_dsl_root_section %Spark.Dsl.Section{
    name: :__agent_message_root__,
    describe: "Defines a complete AgentMessage.",
    schema: [],
    entities: [ @agent_message ],
    top_level?: true
  }

  use Spark.Dsl.Extension,
    sections: [@agent_message_dsl_root_section]
    verifiers: [
      AgentMessage.Verifiers.RootVerifier,
      AgentMessage.Verifiers.AgentContentMessageVerifier,
      AgentMessage.Verifiers.ViewLocationActionVerifier,
      AgentMessage.Verifiers.ComposeActionVerifier,
      AgentMessage.Verifiers.SuggestedActionVerifier,
      AgentMessage.Verifiers.SuggestionVerifier,
      AgentMessage.Verifiers.MediaVerifier,
      AgentMessage.Verifiers.CardContentVerifier,
      AgentMessage.Verifiers.CarouselCardVerifier,
      AgentMessage.Verifiers.StandaloneCardVerifier,
      AgentMessage.Verifiers.RichCardVerifier
    ]
end
```

Is there a any workaround that does _not_ involve changing the property names?

**Comment by svallory** [comment]
> Elixir.AgentMessage.Extension.AgentMessageRoot.AgentMessage.ContentMessage.ContentMessage.RichCard.RichCard.CarouselCard.CarouselCard.CardContent.CardContent.Suggestion.Suggestion.Action.Action.ViewLocationAction.ViewLocationAction.LatLong.LatLong.Options.beam

I'm on the latest version, but I'm still getting this path, which has a lot of repetition

**Comment by zachdaniel** [comment]
oh wow 🤔 Okay, so we fixed it partially, but clearly its duplicating the name.

**Comment by zachdaniel** [comment]
Can you try `main`?

**Comment by svallory** [comment]
WOW! You guys are fast! It works on version 2.2.64! Thank you so much!!
