### ISSUE TITLE
Transformer behaviour error add irrelevant stacktrace

### ISSUE THREAD

**Issue by erikaaus** [ash-project/spark#38]
**Describe the bug**
When a `Spark.Dsl.Transformer.transform/1` callback returns an error, it includes an irrelevant stacktrace.

**To Reproduce**
Here is a minimal example, with a transformer that always fails:

```
defmodule FailingTranformExample.Transformer do
  use Spark.Dsl.Transformer

  def transform(_), do: {:error, %Spark.Error.DslError{message: "fail"}}
end

defmodule FailingTranformExample.Extension do
  defmodule Entity do
    defstruct [:thing]
  end

  @entity %Spark.Dsl.Entity{
    name: :entity,
    target: Entity,
    schema: [thing: [type: :atom, required: true]]
  }
  @section %Spark.Dsl.Section{
    name: :section,
    entities: [@entity],
    top_level?: true
  }

  use Spark.Dsl.Extension,
    sections: [@section],
    transformers: [FailingTranformExample.Transformer]
end

defmodule FailingTranformExample do
  use Spark.Dsl, default_extensions: [extensions: FailingTranformExample.Extension]
end

defmodule FailingTranformExample.Instantiation do
  use FailingTranformExample

  entity do
    thing(:stuff)
  end
end
```

Compiling this example gives this error:

```
== Compilation error in file lib/failing_tranform_example.ex ==
** (Spark.Error.DslError) [FailingTranformExample.Instantiation]
 fail
    (spark 1.1.13) lib/spark/dsl/extension.ex:712: Spark.Dsl.Extension.raise_transformer_error/2
    (elixir 1.14.2) lib/enum.ex:4751: Enumerable.List.reduce/3
    (elixir 1.14.2) lib/enum.ex:2514: Enum.reduce_while/3
    /Users/rowland/projects/failing_tranform_example/lib/failing_tranform_example.ex:32: (file)
    (stdlib 4.1.1) erl_eval.erl:748: :erl_eval.do_apply/7
    (stdlib 4.1.1) erl_eval.erl:961: :erl_eval.expr_list/7
    (stdlib 4.1.1) erl_eval.erl:454: :erl_eval.expr/6
```

Notice that it includes a stacktrace from Spark, not from the instantiating code.

**Expected behavior**
Best case, I would expect the Transformer to error from the instantiating module.
Alternatively, hiding the unhelpful stacktrace would at least allow for better formatted errors for the user.

By contrast, when an Entity's tranform function returns an error:

```
== Compilation error in file lib/failing_tranform_example.ex ==
** (Spark.Error.DslError) [FailingTranformExample.Instantiation]
 section -> entity:
  fails
    lib/failing_tranform_example.ex:41: (module)
    (stdlib 4.1.1) lists.erl:1355: :lists.foldl_1/3
```

Where `lib/failing_transform_example.ex:41` is the instantiating module:

```
defmodule FailingTranformExample.Instantiation do
  use FailingTranformExample

  entity do # this line is line 41
     thing(:stuff)
  end
end
```

**Runtime**
 - Elixir version 1.14.2
 - Erlang version OTP 25 [erts-13.1.2]
 - OS MacOS
 - Spark version 1.1.13

**Comment by zachdaniel** [comment]
Ah, yeah you're right. We talked about this before but I didn't understand. The `raise_transformer_error` stacktrace is definitely useless and should be hidden and/or a proper stacktrace should be captured in the returned error and then raised at that point.
