### ISSUE TITLE
Spark.Formatter requires explicit compilation to work with custom modules

### ISSUE THREAD

**Issue by rbino** [ash-project/spark#78]
**Describe the bug**
When cloning a fresh repo that uses `Spark.Formatter` to format custom resource modules (i.e. like `MyApp.Resource` described [here](https://hexdocs.pm/spark/Spark.Formatter.html)), `mix format` fails if it's not preceded by `mix.compile`.

**To Reproduce**
I've created [a repo](https://github.com/rbino/spark_formatter_bug) to easily reproduce the issue.

```bash
git clone https://github.com/rbino/spark_formatter_bug
cd spark_formatter_bug
mix do deps.get, format
```

fails with

```bash
mix format failed for file: test/test_helper.exs
** (ArgumentError) could not load module SparkFormatterBug.MyResource due to reason :nofile
    (elixir 1.15.7) lib/code.ex:1888: Code.ensure_compiled!/1
    (spark 1.1.55) lib/spark/formatter.ex:64: anonymous fn/1 in Spark.Formatter.format/2
    (elixir 1.15.7) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
    (elixir 1.15.7) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
    (spark 1.1.55) lib/spark/formatter.ex:59: Spark.Formatter.format/2
    (elixir 1.15.7) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mix 1.15.7) lib/mix/tasks/format.ex:629: Mix.Tasks.Format.format_file/2
    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
```

While doing

```
mix do deps.get, compile, format
```

makes it work. Doing `mix.clean` and then `mix.format` recreates the error.

**Expected behavior**
This changes the default behaviour of `mix format` (which doesn't require the compilation of the app), I'd expect this to work with a freshly cloned repo (possibly detecting custom module and forcing a compilation of the application?).

**Runtime**
 - Elixir version: 1.15.7
 - Erlang version: OTP 26.1.2
 - OS: Ubuntu 22.04 LTS
 - Spark version: 1.1.55

**Comment by rbino** [comment]
I minimized the test case further (removing Ash, which was not actually needed to reproduce the bug) and I can confirm the `main` branch fixes the issue, thanks!
